modLoader = 'javafml'
loaderVersion = '[1,)'
license = 'MIT'
showAsResourcePack = false
mods = [
        { modId = 'goldenapple', version = '1.0.0', displayName = 'Golden Apple Recipe', description = 'Restores the enchanted golden apple crafting recipe' },
]
